package com.doit.dao;

import com.doit.pojo.Bar;
import com.doit.pojo.BarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    long countByExample(BarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByExample(BarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByPrimaryKey(String barCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insert(Bar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insertSelective(Bar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    List<Bar> selectByExample(BarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    Bar selectByPrimaryKey(String barCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") Bar record, @Param("example") BarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExample(@Param("record") Bar record, @Param("example") BarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKeySelective(Bar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKey(Bar record);
}