package com.doit.dao;

import com.doit.pojo.Defect;
import com.doit.pojo.DefectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    long countByExample(DefectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByExample(DefectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByPrimaryKey(Integer defectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insert(Defect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insertSelective(Defect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    List<Defect> selectByExample(DefectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    Defect selectByPrimaryKey(Integer defectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") Defect record, @Param("example") DefectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExample(@Param("record") Defect record, @Param("example") DefectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKeySelective(Defect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKey(Defect record);
}