package com.doit.dao;

import com.doit.pojo.InspectionTask;
import com.doit.pojo.InspectionTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InspectionTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    long countByExample(InspectionTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByExample(InspectionTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByPrimaryKey(String inspectionTaskCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insert(InspectionTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insertSelective(InspectionTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    List<InspectionTask> selectByExample(InspectionTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    InspectionTask selectByPrimaryKey(String inspectionTaskCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") InspectionTask record, @Param("example") InspectionTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExample(@Param("record") InspectionTask record, @Param("example") InspectionTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKeySelective(InspectionTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKey(InspectionTask record);
}