package com.doit.dao;

import com.doit.pojo.InspectionResult;
import com.doit.pojo.InspectionResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InspectionResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    long countByExample(InspectionResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByExample(InspectionResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByPrimaryKey(Integer inspectionResultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insert(InspectionResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insertSelective(InspectionResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    List<InspectionResult> selectByExample(InspectionResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    InspectionResult selectByPrimaryKey(Integer inspectionResultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") InspectionResult record, @Param("example") InspectionResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExample(@Param("record") InspectionResult record, @Param("example") InspectionResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKeySelective(InspectionResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKey(InspectionResult record);
}