package com.doit.dao;

import com.doit.pojo.LineUser;
import com.doit.pojo.LineUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LineUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    long countByExample(LineUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByExample(LineUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insert(LineUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insertSelective(LineUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    List<LineUser> selectByExample(LineUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    LineUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") LineUser record, @Param("example") LineUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExample(@Param("record") LineUser record, @Param("example") LineUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKeySelective(LineUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKey(LineUser record);
}