package com.doit.dao;

import com.doit.pojo.ServiceResult;
import com.doit.pojo.ServiceResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    long countByExample(ServiceResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByExample(ServiceResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByPrimaryKey(String serviceResultCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insert(ServiceResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insertSelective(ServiceResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    List<ServiceResult> selectByExample(ServiceResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    ServiceResult selectByPrimaryKey(String serviceResultCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") ServiceResult record, @Param("example") ServiceResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExample(@Param("record") ServiceResult record, @Param("example") ServiceResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKeySelective(ServiceResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKey(ServiceResult record);
}