package com.doit.dao;

import com.doit.pojo.ServiceTask;
import com.doit.pojo.ServiceTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    long countByExample(ServiceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByExample(ServiceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByPrimaryKey(String serviceTaskCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insert(ServiceTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insertSelective(ServiceTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    List<ServiceTask> selectByExample(ServiceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    ServiceTask selectByPrimaryKey(String serviceTaskCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") ServiceTask record, @Param("example") ServiceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExample(@Param("record") ServiceTask record, @Param("example") ServiceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKeySelective(ServiceTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKey(ServiceTask record);
}