package com.doit.dao;

import com.doit.pojo.TaskResut;
import com.doit.pojo.TaskResutExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskResutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_resut
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    long countByExample(TaskResutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_resut
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByExample(TaskResutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_resut
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_resut
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insert(TaskResut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_resut
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insertSelective(TaskResut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_resut
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    List<TaskResut> selectByExample(TaskResutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_resut
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    TaskResut selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_resut
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaskResut record, @Param("example") TaskResutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_resut
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExample(@Param("record") TaskResut record, @Param("example") TaskResutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_resut
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKeySelective(TaskResut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_resut
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKey(TaskResut record);
}