package com.doit.dao;

import com.doit.pojo.TaskUser;
import com.doit.pojo.TaskUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    long countByExample(TaskUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByExample(TaskUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insert(TaskUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int insertSelective(TaskUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    List<TaskUser> selectByExample(TaskUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    TaskUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaskUser record, @Param("example") TaskUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByExample(@Param("record") TaskUser record, @Param("example") TaskUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKeySelective(TaskUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_user
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    int updateByPrimaryKey(TaskUser record);
}