package com.doit.pojo;

public class Bar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bar.bar_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String barCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bar.bar_state
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String barState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bar.line_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String lineCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bar.bar_code
     *
     * @return the value of bar.bar_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bar.bar_code
     *
     * @param barCode the value for bar.bar_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bar.bar_state
     *
     * @return the value of bar.bar_state
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getBarState() {
        return barState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bar.bar_state
     *
     * @param barState the value for bar.bar_state
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setBarState(String barState) {
        this.barState = barState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bar.line_code
     *
     * @return the value of bar.line_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getLineCode() {
        return lineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bar.line_code
     *
     * @param lineCode the value for bar.line_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setLineCode(String lineCode) {
        this.lineCode = lineCode;
    }
}