package com.doit.pojo;

import java.util.ArrayList;
import java.util.List;

public class DefectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public DefectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDefectIdIsNull() {
            addCriterion("defect_id is null");
            return (Criteria) this;
        }

        public Criteria andDefectIdIsNotNull() {
            addCriterion("defect_id is not null");
            return (Criteria) this;
        }

        public Criteria andDefectIdEqualTo(Integer value) {
            addCriterion("defect_id =", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdNotEqualTo(Integer value) {
            addCriterion("defect_id <>", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdGreaterThan(Integer value) {
            addCriterion("defect_id >", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("defect_id >=", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdLessThan(Integer value) {
            addCriterion("defect_id <", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdLessThanOrEqualTo(Integer value) {
            addCriterion("defect_id <=", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdIn(List<Integer> values) {
            addCriterion("defect_id in", values, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdNotIn(List<Integer> values) {
            addCriterion("defect_id not in", values, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdBetween(Integer value1, Integer value2) {
            addCriterion("defect_id between", value1, value2, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("defect_id not between", value1, value2, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectTypeIsNull() {
            addCriterion("defect_type is null");
            return (Criteria) this;
        }

        public Criteria andDefectTypeIsNotNull() {
            addCriterion("defect_type is not null");
            return (Criteria) this;
        }

        public Criteria andDefectTypeEqualTo(String value) {
            addCriterion("defect_type =", value, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeNotEqualTo(String value) {
            addCriterion("defect_type <>", value, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeGreaterThan(String value) {
            addCriterion("defect_type >", value, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeGreaterThanOrEqualTo(String value) {
            addCriterion("defect_type >=", value, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeLessThan(String value) {
            addCriterion("defect_type <", value, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeLessThanOrEqualTo(String value) {
            addCriterion("defect_type <=", value, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeLike(String value) {
            addCriterion("defect_type like", value, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeNotLike(String value) {
            addCriterion("defect_type not like", value, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeIn(List<String> values) {
            addCriterion("defect_type in", values, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeNotIn(List<String> values) {
            addCriterion("defect_type not in", values, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeBetween(String value1, String value2) {
            addCriterion("defect_type between", value1, value2, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeNotBetween(String value1, String value2) {
            addCriterion("defect_type not between", value1, value2, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectStateIsNull() {
            addCriterion("defect_state is null");
            return (Criteria) this;
        }

        public Criteria andDefectStateIsNotNull() {
            addCriterion("defect_state is not null");
            return (Criteria) this;
        }

        public Criteria andDefectStateEqualTo(String value) {
            addCriterion("defect_state =", value, "defectState");
            return (Criteria) this;
        }

        public Criteria andDefectStateNotEqualTo(String value) {
            addCriterion("defect_state <>", value, "defectState");
            return (Criteria) this;
        }

        public Criteria andDefectStateGreaterThan(String value) {
            addCriterion("defect_state >", value, "defectState");
            return (Criteria) this;
        }

        public Criteria andDefectStateGreaterThanOrEqualTo(String value) {
            addCriterion("defect_state >=", value, "defectState");
            return (Criteria) this;
        }

        public Criteria andDefectStateLessThan(String value) {
            addCriterion("defect_state <", value, "defectState");
            return (Criteria) this;
        }

        public Criteria andDefectStateLessThanOrEqualTo(String value) {
            addCriterion("defect_state <=", value, "defectState");
            return (Criteria) this;
        }

        public Criteria andDefectStateLike(String value) {
            addCriterion("defect_state like", value, "defectState");
            return (Criteria) this;
        }

        public Criteria andDefectStateNotLike(String value) {
            addCriterion("defect_state not like", value, "defectState");
            return (Criteria) this;
        }

        public Criteria andDefectStateIn(List<String> values) {
            addCriterion("defect_state in", values, "defectState");
            return (Criteria) this;
        }

        public Criteria andDefectStateNotIn(List<String> values) {
            addCriterion("defect_state not in", values, "defectState");
            return (Criteria) this;
        }

        public Criteria andDefectStateBetween(String value1, String value2) {
            addCriterion("defect_state between", value1, value2, "defectState");
            return (Criteria) this;
        }

        public Criteria andDefectStateNotBetween(String value1, String value2) {
            addCriterion("defect_state not between", value1, value2, "defectState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table defect
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 23 09:16:48 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table defect
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}