package com.doit.pojo;

public class Defect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defect.defect_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Integer defectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defect.defect_type
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String defectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defect.defect_state
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String defectState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defect.defect_id
     *
     * @return the value of defect.defect_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Integer getDefectId() {
        return defectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defect.defect_id
     *
     * @param defectId the value for defect.defect_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setDefectId(Integer defectId) {
        this.defectId = defectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defect.defect_type
     *
     * @return the value of defect.defect_type
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getDefectType() {
        return defectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defect.defect_type
     *
     * @param defectType the value for defect.defect_type
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setDefectType(String defectType) {
        this.defectType = defectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defect.defect_state
     *
     * @return the value of defect.defect_state
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getDefectState() {
        return defectState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defect.defect_state
     *
     * @param defectState the value for defect.defect_state
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setDefectState(String defectState) {
        this.defectState = defectState;
    }
}