package com.doit.pojo;

import java.util.Date;

public class InspectionTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspection_task.inspection_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String inspectionTaskCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspection_task.inspection_task_name
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String inspectionTaskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspection_task.line_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String lineCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspection_task.inspection_task_startbar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String inspectionTaskStartbar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspection_task.inspection_task_endbar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String inspectionTaskEndbar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspection_task.inspection_task_release_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Date inspectionTaskReleaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspection_task.inspection_task_remark
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String inspectionTaskRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspection_task.inspection_task_executor
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String inspectionTaskExecutor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspection_task.inspection_task_code
     *
     * @return the value of inspection_task.inspection_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getInspectionTaskCode() {
        return inspectionTaskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspection_task.inspection_task_code
     *
     * @param inspectionTaskCode the value for inspection_task.inspection_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setInspectionTaskCode(String inspectionTaskCode) {
        this.inspectionTaskCode = inspectionTaskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspection_task.inspection_task_name
     *
     * @return the value of inspection_task.inspection_task_name
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getInspectionTaskName() {
        return inspectionTaskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspection_task.inspection_task_name
     *
     * @param inspectionTaskName the value for inspection_task.inspection_task_name
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setInspectionTaskName(String inspectionTaskName) {
        this.inspectionTaskName = inspectionTaskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspection_task.line_code
     *
     * @return the value of inspection_task.line_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getLineCode() {
        return lineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspection_task.line_code
     *
     * @param lineCode the value for inspection_task.line_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setLineCode(String lineCode) {
        this.lineCode = lineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspection_task.inspection_task_startbar
     *
     * @return the value of inspection_task.inspection_task_startbar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getInspectionTaskStartbar() {
        return inspectionTaskStartbar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspection_task.inspection_task_startbar
     *
     * @param inspectionTaskStartbar the value for inspection_task.inspection_task_startbar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setInspectionTaskStartbar(String inspectionTaskStartbar) {
        this.inspectionTaskStartbar = inspectionTaskStartbar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspection_task.inspection_task_endbar
     *
     * @return the value of inspection_task.inspection_task_endbar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getInspectionTaskEndbar() {
        return inspectionTaskEndbar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspection_task.inspection_task_endbar
     *
     * @param inspectionTaskEndbar the value for inspection_task.inspection_task_endbar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setInspectionTaskEndbar(String inspectionTaskEndbar) {
        this.inspectionTaskEndbar = inspectionTaskEndbar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspection_task.inspection_task_release_date
     *
     * @return the value of inspection_task.inspection_task_release_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Date getInspectionTaskReleaseDate() {
        return inspectionTaskReleaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspection_task.inspection_task_release_date
     *
     * @param inspectionTaskReleaseDate the value for inspection_task.inspection_task_release_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setInspectionTaskReleaseDate(Date inspectionTaskReleaseDate) {
        this.inspectionTaskReleaseDate = inspectionTaskReleaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspection_task.inspection_task_remark
     *
     * @return the value of inspection_task.inspection_task_remark
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getInspectionTaskRemark() {
        return inspectionTaskRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspection_task.inspection_task_remark
     *
     * @param inspectionTaskRemark the value for inspection_task.inspection_task_remark
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setInspectionTaskRemark(String inspectionTaskRemark) {
        this.inspectionTaskRemark = inspectionTaskRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspection_task.inspection_task_executor
     *
     * @return the value of inspection_task.inspection_task_executor
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getInspectionTaskExecutor() {
        return inspectionTaskExecutor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspection_task.inspection_task_executor
     *
     * @param inspectionTaskExecutor the value for inspection_task.inspection_task_executor
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setInspectionTaskExecutor(String inspectionTaskExecutor) {
        this.inspectionTaskExecutor = inspectionTaskExecutor;
    }
}