package com.doit.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class InspectionResultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public InspectionResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andInspectionResultIdIsNull() {
            addCriterion("inspection_result_id is null");
            return (Criteria) this;
        }

        public Criteria andInspectionResultIdIsNotNull() {
            addCriterion("inspection_result_id is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionResultIdEqualTo(Integer value) {
            addCriterion("inspection_result_id =", value, "inspectionResultId");
            return (Criteria) this;
        }

        public Criteria andInspectionResultIdNotEqualTo(Integer value) {
            addCriterion("inspection_result_id <>", value, "inspectionResultId");
            return (Criteria) this;
        }

        public Criteria andInspectionResultIdGreaterThan(Integer value) {
            addCriterion("inspection_result_id >", value, "inspectionResultId");
            return (Criteria) this;
        }

        public Criteria andInspectionResultIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("inspection_result_id >=", value, "inspectionResultId");
            return (Criteria) this;
        }

        public Criteria andInspectionResultIdLessThan(Integer value) {
            addCriterion("inspection_result_id <", value, "inspectionResultId");
            return (Criteria) this;
        }

        public Criteria andInspectionResultIdLessThanOrEqualTo(Integer value) {
            addCriterion("inspection_result_id <=", value, "inspectionResultId");
            return (Criteria) this;
        }

        public Criteria andInspectionResultIdIn(List<Integer> values) {
            addCriterion("inspection_result_id in", values, "inspectionResultId");
            return (Criteria) this;
        }

        public Criteria andInspectionResultIdNotIn(List<Integer> values) {
            addCriterion("inspection_result_id not in", values, "inspectionResultId");
            return (Criteria) this;
        }

        public Criteria andInspectionResultIdBetween(Integer value1, Integer value2) {
            addCriterion("inspection_result_id between", value1, value2, "inspectionResultId");
            return (Criteria) this;
        }

        public Criteria andInspectionResultIdNotBetween(Integer value1, Integer value2) {
            addCriterion("inspection_result_id not between", value1, value2, "inspectionResultId");
            return (Criteria) this;
        }

        public Criteria andInspectionTaskCodeIsNull() {
            addCriterion("inspection_task_code is null");
            return (Criteria) this;
        }

        public Criteria andInspectionTaskCodeIsNotNull() {
            addCriterion("inspection_task_code is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionTaskCodeEqualTo(String value) {
            addCriterion("inspection_task_code =", value, "inspectionTaskCode");
            return (Criteria) this;
        }

        public Criteria andInspectionTaskCodeNotEqualTo(String value) {
            addCriterion("inspection_task_code <>", value, "inspectionTaskCode");
            return (Criteria) this;
        }

        public Criteria andInspectionTaskCodeGreaterThan(String value) {
            addCriterion("inspection_task_code >", value, "inspectionTaskCode");
            return (Criteria) this;
        }

        public Criteria andInspectionTaskCodeGreaterThanOrEqualTo(String value) {
            addCriterion("inspection_task_code >=", value, "inspectionTaskCode");
            return (Criteria) this;
        }

        public Criteria andInspectionTaskCodeLessThan(String value) {
            addCriterion("inspection_task_code <", value, "inspectionTaskCode");
            return (Criteria) this;
        }

        public Criteria andInspectionTaskCodeLessThanOrEqualTo(String value) {
            addCriterion("inspection_task_code <=", value, "inspectionTaskCode");
            return (Criteria) this;
        }

        public Criteria andInspectionTaskCodeLike(String value) {
            addCriterion("inspection_task_code like", value, "inspectionTaskCode");
            return (Criteria) this;
        }

        public Criteria andInspectionTaskCodeNotLike(String value) {
            addCriterion("inspection_task_code not like", value, "inspectionTaskCode");
            return (Criteria) this;
        }

        public Criteria andInspectionTaskCodeIn(List<String> values) {
            addCriterion("inspection_task_code in", values, "inspectionTaskCode");
            return (Criteria) this;
        }

        public Criteria andInspectionTaskCodeNotIn(List<String> values) {
            addCriterion("inspection_task_code not in", values, "inspectionTaskCode");
            return (Criteria) this;
        }

        public Criteria andInspectionTaskCodeBetween(String value1, String value2) {
            addCriterion("inspection_task_code between", value1, value2, "inspectionTaskCode");
            return (Criteria) this;
        }

        public Criteria andInspectionTaskCodeNotBetween(String value1, String value2) {
            addCriterion("inspection_task_code not between", value1, value2, "inspectionTaskCode");
            return (Criteria) this;
        }

        public Criteria andInlineCodeIsNull() {
            addCriterion("inline_code is null");
            return (Criteria) this;
        }

        public Criteria andInlineCodeIsNotNull() {
            addCriterion("inline_code is not null");
            return (Criteria) this;
        }

        public Criteria andInlineCodeEqualTo(String value) {
            addCriterion("inline_code =", value, "inlineCode");
            return (Criteria) this;
        }

        public Criteria andInlineCodeNotEqualTo(String value) {
            addCriterion("inline_code <>", value, "inlineCode");
            return (Criteria) this;
        }

        public Criteria andInlineCodeGreaterThan(String value) {
            addCriterion("inline_code >", value, "inlineCode");
            return (Criteria) this;
        }

        public Criteria andInlineCodeGreaterThanOrEqualTo(String value) {
            addCriterion("inline_code >=", value, "inlineCode");
            return (Criteria) this;
        }

        public Criteria andInlineCodeLessThan(String value) {
            addCriterion("inline_code <", value, "inlineCode");
            return (Criteria) this;
        }

        public Criteria andInlineCodeLessThanOrEqualTo(String value) {
            addCriterion("inline_code <=", value, "inlineCode");
            return (Criteria) this;
        }

        public Criteria andInlineCodeLike(String value) {
            addCriterion("inline_code like", value, "inlineCode");
            return (Criteria) this;
        }

        public Criteria andInlineCodeNotLike(String value) {
            addCriterion("inline_code not like", value, "inlineCode");
            return (Criteria) this;
        }

        public Criteria andInlineCodeIn(List<String> values) {
            addCriterion("inline_code in", values, "inlineCode");
            return (Criteria) this;
        }

        public Criteria andInlineCodeNotIn(List<String> values) {
            addCriterion("inline_code not in", values, "inlineCode");
            return (Criteria) this;
        }

        public Criteria andInlineCodeBetween(String value1, String value2) {
            addCriterion("inline_code between", value1, value2, "inlineCode");
            return (Criteria) this;
        }

        public Criteria andInlineCodeNotBetween(String value1, String value2) {
            addCriterion("inline_code not between", value1, value2, "inlineCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeIsNull() {
            addCriterion("bar_code is null");
            return (Criteria) this;
        }

        public Criteria andBarCodeIsNotNull() {
            addCriterion("bar_code is not null");
            return (Criteria) this;
        }

        public Criteria andBarCodeEqualTo(String value) {
            addCriterion("bar_code =", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotEqualTo(String value) {
            addCriterion("bar_code <>", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeGreaterThan(String value) {
            addCriterion("bar_code >", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeGreaterThanOrEqualTo(String value) {
            addCriterion("bar_code >=", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeLessThan(String value) {
            addCriterion("bar_code <", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeLessThanOrEqualTo(String value) {
            addCriterion("bar_code <=", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeLike(String value) {
            addCriterion("bar_code like", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotLike(String value) {
            addCriterion("bar_code not like", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeIn(List<String> values) {
            addCriterion("bar_code in", values, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotIn(List<String> values) {
            addCriterion("bar_code not in", values, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeBetween(String value1, String value2) {
            addCriterion("bar_code between", value1, value2, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotBetween(String value1, String value2) {
            addCriterion("bar_code not between", value1, value2, "barCode");
            return (Criteria) this;
        }

        public Criteria andInspectionResultDescriptionIsNull() {
            addCriterion("inspection_result_description is null");
            return (Criteria) this;
        }

        public Criteria andInspectionResultDescriptionIsNotNull() {
            addCriterion("inspection_result_description is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionResultDescriptionEqualTo(String value) {
            addCriterion("inspection_result_description =", value, "inspectionResultDescription");
            return (Criteria) this;
        }

        public Criteria andInspectionResultDescriptionNotEqualTo(String value) {
            addCriterion("inspection_result_description <>", value, "inspectionResultDescription");
            return (Criteria) this;
        }

        public Criteria andInspectionResultDescriptionGreaterThan(String value) {
            addCriterion("inspection_result_description >", value, "inspectionResultDescription");
            return (Criteria) this;
        }

        public Criteria andInspectionResultDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("inspection_result_description >=", value, "inspectionResultDescription");
            return (Criteria) this;
        }

        public Criteria andInspectionResultDescriptionLessThan(String value) {
            addCriterion("inspection_result_description <", value, "inspectionResultDescription");
            return (Criteria) this;
        }

        public Criteria andInspectionResultDescriptionLessThanOrEqualTo(String value) {
            addCriterion("inspection_result_description <=", value, "inspectionResultDescription");
            return (Criteria) this;
        }

        public Criteria andInspectionResultDescriptionLike(String value) {
            addCriterion("inspection_result_description like", value, "inspectionResultDescription");
            return (Criteria) this;
        }

        public Criteria andInspectionResultDescriptionNotLike(String value) {
            addCriterion("inspection_result_description not like", value, "inspectionResultDescription");
            return (Criteria) this;
        }

        public Criteria andInspectionResultDescriptionIn(List<String> values) {
            addCriterion("inspection_result_description in", values, "inspectionResultDescription");
            return (Criteria) this;
        }

        public Criteria andInspectionResultDescriptionNotIn(List<String> values) {
            addCriterion("inspection_result_description not in", values, "inspectionResultDescription");
            return (Criteria) this;
        }

        public Criteria andInspectionResultDescriptionBetween(String value1, String value2) {
            addCriterion("inspection_result_description between", value1, value2, "inspectionResultDescription");
            return (Criteria) this;
        }

        public Criteria andInspectionResultDescriptionNotBetween(String value1, String value2) {
            addCriterion("inspection_result_description not between", value1, value2, "inspectionResultDescription");
            return (Criteria) this;
        }

        public Criteria andInspectionResultCompletionDateIsNull() {
            addCriterion("inspection_result_completion_date is null");
            return (Criteria) this;
        }

        public Criteria andInspectionResultCompletionDateIsNotNull() {
            addCriterion("inspection_result_completion_date is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionResultCompletionDateEqualTo(Date value) {
            addCriterionForJDBCDate("inspection_result_completion_date =", value, "inspectionResultCompletionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionResultCompletionDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("inspection_result_completion_date <>", value, "inspectionResultCompletionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionResultCompletionDateGreaterThan(Date value) {
            addCriterionForJDBCDate("inspection_result_completion_date >", value, "inspectionResultCompletionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionResultCompletionDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("inspection_result_completion_date >=", value, "inspectionResultCompletionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionResultCompletionDateLessThan(Date value) {
            addCriterionForJDBCDate("inspection_result_completion_date <", value, "inspectionResultCompletionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionResultCompletionDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("inspection_result_completion_date <=", value, "inspectionResultCompletionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionResultCompletionDateIn(List<Date> values) {
            addCriterionForJDBCDate("inspection_result_completion_date in", values, "inspectionResultCompletionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionResultCompletionDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("inspection_result_completion_date not in", values, "inspectionResultCompletionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionResultCompletionDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("inspection_result_completion_date between", value1, value2, "inspectionResultCompletionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionResultCompletionDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("inspection_result_completion_date not between", value1, value2, "inspectionResultCompletionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionResultStateIsNull() {
            addCriterion("inspection_result_state is null");
            return (Criteria) this;
        }

        public Criteria andInspectionResultStateIsNotNull() {
            addCriterion("inspection_result_state is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionResultStateEqualTo(String value) {
            addCriterion("inspection_result_state =", value, "inspectionResultState");
            return (Criteria) this;
        }

        public Criteria andInspectionResultStateNotEqualTo(String value) {
            addCriterion("inspection_result_state <>", value, "inspectionResultState");
            return (Criteria) this;
        }

        public Criteria andInspectionResultStateGreaterThan(String value) {
            addCriterion("inspection_result_state >", value, "inspectionResultState");
            return (Criteria) this;
        }

        public Criteria andInspectionResultStateGreaterThanOrEqualTo(String value) {
            addCriterion("inspection_result_state >=", value, "inspectionResultState");
            return (Criteria) this;
        }

        public Criteria andInspectionResultStateLessThan(String value) {
            addCriterion("inspection_result_state <", value, "inspectionResultState");
            return (Criteria) this;
        }

        public Criteria andInspectionResultStateLessThanOrEqualTo(String value) {
            addCriterion("inspection_result_state <=", value, "inspectionResultState");
            return (Criteria) this;
        }

        public Criteria andInspectionResultStateLike(String value) {
            addCriterion("inspection_result_state like", value, "inspectionResultState");
            return (Criteria) this;
        }

        public Criteria andInspectionResultStateNotLike(String value) {
            addCriterion("inspection_result_state not like", value, "inspectionResultState");
            return (Criteria) this;
        }

        public Criteria andInspectionResultStateIn(List<String> values) {
            addCriterion("inspection_result_state in", values, "inspectionResultState");
            return (Criteria) this;
        }

        public Criteria andInspectionResultStateNotIn(List<String> values) {
            addCriterion("inspection_result_state not in", values, "inspectionResultState");
            return (Criteria) this;
        }

        public Criteria andInspectionResultStateBetween(String value1, String value2) {
            addCriterion("inspection_result_state between", value1, value2, "inspectionResultState");
            return (Criteria) this;
        }

        public Criteria andInspectionResultStateNotBetween(String value1, String value2) {
            addCriterion("inspection_result_state not between", value1, value2, "inspectionResultState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inspection_result
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 23 09:16:48 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inspection_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}