package com.doit.pojo;

import java.util.Date;

public class InspectionResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspection_result.inspection_result_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Integer inspectionResultId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspection_result.inspection_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String inspectionTaskCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspection_result.inline_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String inlineCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspection_result.bar_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String barCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspection_result.inspection_result_description
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String inspectionResultDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspection_result.inspection_result_completion_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Date inspectionResultCompletionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspection_result.inspection_result_state
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String inspectionResultState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspection_result.inspection_result_id
     *
     * @return the value of inspection_result.inspection_result_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Integer getInspectionResultId() {
        return inspectionResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspection_result.inspection_result_id
     *
     * @param inspectionResultId the value for inspection_result.inspection_result_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setInspectionResultId(Integer inspectionResultId) {
        this.inspectionResultId = inspectionResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspection_result.inspection_task_code
     *
     * @return the value of inspection_result.inspection_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getInspectionTaskCode() {
        return inspectionTaskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspection_result.inspection_task_code
     *
     * @param inspectionTaskCode the value for inspection_result.inspection_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setInspectionTaskCode(String inspectionTaskCode) {
        this.inspectionTaskCode = inspectionTaskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspection_result.inline_code
     *
     * @return the value of inspection_result.inline_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getInlineCode() {
        return inlineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspection_result.inline_code
     *
     * @param inlineCode the value for inspection_result.inline_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setInlineCode(String inlineCode) {
        this.inlineCode = inlineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspection_result.bar_code
     *
     * @return the value of inspection_result.bar_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspection_result.bar_code
     *
     * @param barCode the value for inspection_result.bar_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspection_result.inspection_result_description
     *
     * @return the value of inspection_result.inspection_result_description
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getInspectionResultDescription() {
        return inspectionResultDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspection_result.inspection_result_description
     *
     * @param inspectionResultDescription the value for inspection_result.inspection_result_description
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setInspectionResultDescription(String inspectionResultDescription) {
        this.inspectionResultDescription = inspectionResultDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspection_result.inspection_result_completion_date
     *
     * @return the value of inspection_result.inspection_result_completion_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Date getInspectionResultCompletionDate() {
        return inspectionResultCompletionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspection_result.inspection_result_completion_date
     *
     * @param inspectionResultCompletionDate the value for inspection_result.inspection_result_completion_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setInspectionResultCompletionDate(Date inspectionResultCompletionDate) {
        this.inspectionResultCompletionDate = inspectionResultCompletionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspection_result.inspection_result_state
     *
     * @return the value of inspection_result.inspection_result_state
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getInspectionResultState() {
        return inspectionResultState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspection_result.inspection_result_state
     *
     * @param inspectionResultState the value for inspection_result.inspection_result_state
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setInspectionResultState(String inspectionResultState) {
        this.inspectionResultState = inspectionResultState;
    }
}