package com.doit.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class LineExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table line
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table line
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table line
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public LineExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table line
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andLineCodeIsNull() {
            addCriterion("line_code is null");
            return (Criteria) this;
        }

        public Criteria andLineCodeIsNotNull() {
            addCriterion("line_code is not null");
            return (Criteria) this;
        }

        public Criteria andLineCodeEqualTo(String value) {
            addCriterion("line_code =", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeNotEqualTo(String value) {
            addCriterion("line_code <>", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeGreaterThan(String value) {
            addCriterion("line_code >", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeGreaterThanOrEqualTo(String value) {
            addCriterion("line_code >=", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeLessThan(String value) {
            addCriterion("line_code <", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeLessThanOrEqualTo(String value) {
            addCriterion("line_code <=", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeLike(String value) {
            addCriterion("line_code like", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeNotLike(String value) {
            addCriterion("line_code not like", value, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeIn(List<String> values) {
            addCriterion("line_code in", values, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeNotIn(List<String> values) {
            addCriterion("line_code not in", values, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeBetween(String value1, String value2) {
            addCriterion("line_code between", value1, value2, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineCodeNotBetween(String value1, String value2) {
            addCriterion("line_code not between", value1, value2, "lineCode");
            return (Criteria) this;
        }

        public Criteria andLineNameIsNull() {
            addCriterion("line_name is null");
            return (Criteria) this;
        }

        public Criteria andLineNameIsNotNull() {
            addCriterion("line_name is not null");
            return (Criteria) this;
        }

        public Criteria andLineNameEqualTo(String value) {
            addCriterion("line_name =", value, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameNotEqualTo(String value) {
            addCriterion("line_name <>", value, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameGreaterThan(String value) {
            addCriterion("line_name >", value, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameGreaterThanOrEqualTo(String value) {
            addCriterion("line_name >=", value, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameLessThan(String value) {
            addCriterion("line_name <", value, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameLessThanOrEqualTo(String value) {
            addCriterion("line_name <=", value, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameLike(String value) {
            addCriterion("line_name like", value, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameNotLike(String value) {
            addCriterion("line_name not like", value, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameIn(List<String> values) {
            addCriterion("line_name in", values, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameNotIn(List<String> values) {
            addCriterion("line_name not in", values, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameBetween(String value1, String value2) {
            addCriterion("line_name between", value1, value2, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameNotBetween(String value1, String value2) {
            addCriterion("line_name not between", value1, value2, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineLengthIsNull() {
            addCriterion("line_length is null");
            return (Criteria) this;
        }

        public Criteria andLineLengthIsNotNull() {
            addCriterion("line_length is not null");
            return (Criteria) this;
        }

        public Criteria andLineLengthEqualTo(Integer value) {
            addCriterion("line_length =", value, "lineLength");
            return (Criteria) this;
        }

        public Criteria andLineLengthNotEqualTo(Integer value) {
            addCriterion("line_length <>", value, "lineLength");
            return (Criteria) this;
        }

        public Criteria andLineLengthGreaterThan(Integer value) {
            addCriterion("line_length >", value, "lineLength");
            return (Criteria) this;
        }

        public Criteria andLineLengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("line_length >=", value, "lineLength");
            return (Criteria) this;
        }

        public Criteria andLineLengthLessThan(Integer value) {
            addCriterion("line_length <", value, "lineLength");
            return (Criteria) this;
        }

        public Criteria andLineLengthLessThanOrEqualTo(Integer value) {
            addCriterion("line_length <=", value, "lineLength");
            return (Criteria) this;
        }

        public Criteria andLineLengthIn(List<Integer> values) {
            addCriterion("line_length in", values, "lineLength");
            return (Criteria) this;
        }

        public Criteria andLineLengthNotIn(List<Integer> values) {
            addCriterion("line_length not in", values, "lineLength");
            return (Criteria) this;
        }

        public Criteria andLineLengthBetween(Integer value1, Integer value2) {
            addCriterion("line_length between", value1, value2, "lineLength");
            return (Criteria) this;
        }

        public Criteria andLineLengthNotBetween(Integer value1, Integer value2) {
            addCriterion("line_length not between", value1, value2, "lineLength");
            return (Criteria) this;
        }

        public Criteria andLineRundateIsNull() {
            addCriterion("line_rundate is null");
            return (Criteria) this;
        }

        public Criteria andLineRundateIsNotNull() {
            addCriterion("line_rundate is not null");
            return (Criteria) this;
        }

        public Criteria andLineRundateEqualTo(Date value) {
            addCriterionForJDBCDate("line_rundate =", value, "lineRundate");
            return (Criteria) this;
        }

        public Criteria andLineRundateNotEqualTo(Date value) {
            addCriterionForJDBCDate("line_rundate <>", value, "lineRundate");
            return (Criteria) this;
        }

        public Criteria andLineRundateGreaterThan(Date value) {
            addCriterionForJDBCDate("line_rundate >", value, "lineRundate");
            return (Criteria) this;
        }

        public Criteria andLineRundateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("line_rundate >=", value, "lineRundate");
            return (Criteria) this;
        }

        public Criteria andLineRundateLessThan(Date value) {
            addCriterionForJDBCDate("line_rundate <", value, "lineRundate");
            return (Criteria) this;
        }

        public Criteria andLineRundateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("line_rundate <=", value, "lineRundate");
            return (Criteria) this;
        }

        public Criteria andLineRundateIn(List<Date> values) {
            addCriterionForJDBCDate("line_rundate in", values, "lineRundate");
            return (Criteria) this;
        }

        public Criteria andLineRundateNotIn(List<Date> values) {
            addCriterionForJDBCDate("line_rundate not in", values, "lineRundate");
            return (Criteria) this;
        }

        public Criteria andLineRundateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("line_rundate between", value1, value2, "lineRundate");
            return (Criteria) this;
        }

        public Criteria andLineRundateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("line_rundate not between", value1, value2, "lineRundate");
            return (Criteria) this;
        }

        public Criteria andLineVoltageLevelIsNull() {
            addCriterion("line_voltage_level is null");
            return (Criteria) this;
        }

        public Criteria andLineVoltageLevelIsNotNull() {
            addCriterion("line_voltage_level is not null");
            return (Criteria) this;
        }

        public Criteria andLineVoltageLevelEqualTo(String value) {
            addCriterion("line_voltage_level =", value, "lineVoltageLevel");
            return (Criteria) this;
        }

        public Criteria andLineVoltageLevelNotEqualTo(String value) {
            addCriterion("line_voltage_level <>", value, "lineVoltageLevel");
            return (Criteria) this;
        }

        public Criteria andLineVoltageLevelGreaterThan(String value) {
            addCriterion("line_voltage_level >", value, "lineVoltageLevel");
            return (Criteria) this;
        }

        public Criteria andLineVoltageLevelGreaterThanOrEqualTo(String value) {
            addCriterion("line_voltage_level >=", value, "lineVoltageLevel");
            return (Criteria) this;
        }

        public Criteria andLineVoltageLevelLessThan(String value) {
            addCriterion("line_voltage_level <", value, "lineVoltageLevel");
            return (Criteria) this;
        }

        public Criteria andLineVoltageLevelLessThanOrEqualTo(String value) {
            addCriterion("line_voltage_level <=", value, "lineVoltageLevel");
            return (Criteria) this;
        }

        public Criteria andLineVoltageLevelLike(String value) {
            addCriterion("line_voltage_level like", value, "lineVoltageLevel");
            return (Criteria) this;
        }

        public Criteria andLineVoltageLevelNotLike(String value) {
            addCriterion("line_voltage_level not like", value, "lineVoltageLevel");
            return (Criteria) this;
        }

        public Criteria andLineVoltageLevelIn(List<String> values) {
            addCriterion("line_voltage_level in", values, "lineVoltageLevel");
            return (Criteria) this;
        }

        public Criteria andLineVoltageLevelNotIn(List<String> values) {
            addCriterion("line_voltage_level not in", values, "lineVoltageLevel");
            return (Criteria) this;
        }

        public Criteria andLineVoltageLevelBetween(String value1, String value2) {
            addCriterion("line_voltage_level between", value1, value2, "lineVoltageLevel");
            return (Criteria) this;
        }

        public Criteria andLineVoltageLevelNotBetween(String value1, String value2) {
            addCriterion("line_voltage_level not between", value1, value2, "lineVoltageLevel");
            return (Criteria) this;
        }

        public Criteria andLineStartBarIsNull() {
            addCriterion("line_start_bar is null");
            return (Criteria) this;
        }

        public Criteria andLineStartBarIsNotNull() {
            addCriterion("line_start_bar is not null");
            return (Criteria) this;
        }

        public Criteria andLineStartBarEqualTo(String value) {
            addCriterion("line_start_bar =", value, "lineStartBar");
            return (Criteria) this;
        }

        public Criteria andLineStartBarNotEqualTo(String value) {
            addCriterion("line_start_bar <>", value, "lineStartBar");
            return (Criteria) this;
        }

        public Criteria andLineStartBarGreaterThan(String value) {
            addCriterion("line_start_bar >", value, "lineStartBar");
            return (Criteria) this;
        }

        public Criteria andLineStartBarGreaterThanOrEqualTo(String value) {
            addCriterion("line_start_bar >=", value, "lineStartBar");
            return (Criteria) this;
        }

        public Criteria andLineStartBarLessThan(String value) {
            addCriterion("line_start_bar <", value, "lineStartBar");
            return (Criteria) this;
        }

        public Criteria andLineStartBarLessThanOrEqualTo(String value) {
            addCriterion("line_start_bar <=", value, "lineStartBar");
            return (Criteria) this;
        }

        public Criteria andLineStartBarLike(String value) {
            addCriterion("line_start_bar like", value, "lineStartBar");
            return (Criteria) this;
        }

        public Criteria andLineStartBarNotLike(String value) {
            addCriterion("line_start_bar not like", value, "lineStartBar");
            return (Criteria) this;
        }

        public Criteria andLineStartBarIn(List<String> values) {
            addCriterion("line_start_bar in", values, "lineStartBar");
            return (Criteria) this;
        }

        public Criteria andLineStartBarNotIn(List<String> values) {
            addCriterion("line_start_bar not in", values, "lineStartBar");
            return (Criteria) this;
        }

        public Criteria andLineStartBarBetween(String value1, String value2) {
            addCriterion("line_start_bar between", value1, value2, "lineStartBar");
            return (Criteria) this;
        }

        public Criteria andLineStartBarNotBetween(String value1, String value2) {
            addCriterion("line_start_bar not between", value1, value2, "lineStartBar");
            return (Criteria) this;
        }

        public Criteria andLineEndBarIsNull() {
            addCriterion("line_end_bar is null");
            return (Criteria) this;
        }

        public Criteria andLineEndBarIsNotNull() {
            addCriterion("line_end_bar is not null");
            return (Criteria) this;
        }

        public Criteria andLineEndBarEqualTo(String value) {
            addCriterion("line_end_bar =", value, "lineEndBar");
            return (Criteria) this;
        }

        public Criteria andLineEndBarNotEqualTo(String value) {
            addCriterion("line_end_bar <>", value, "lineEndBar");
            return (Criteria) this;
        }

        public Criteria andLineEndBarGreaterThan(String value) {
            addCriterion("line_end_bar >", value, "lineEndBar");
            return (Criteria) this;
        }

        public Criteria andLineEndBarGreaterThanOrEqualTo(String value) {
            addCriterion("line_end_bar >=", value, "lineEndBar");
            return (Criteria) this;
        }

        public Criteria andLineEndBarLessThan(String value) {
            addCriterion("line_end_bar <", value, "lineEndBar");
            return (Criteria) this;
        }

        public Criteria andLineEndBarLessThanOrEqualTo(String value) {
            addCriterion("line_end_bar <=", value, "lineEndBar");
            return (Criteria) this;
        }

        public Criteria andLineEndBarLike(String value) {
            addCriterion("line_end_bar like", value, "lineEndBar");
            return (Criteria) this;
        }

        public Criteria andLineEndBarNotLike(String value) {
            addCriterion("line_end_bar not like", value, "lineEndBar");
            return (Criteria) this;
        }

        public Criteria andLineEndBarIn(List<String> values) {
            addCriterion("line_end_bar in", values, "lineEndBar");
            return (Criteria) this;
        }

        public Criteria andLineEndBarNotIn(List<String> values) {
            addCriterion("line_end_bar not in", values, "lineEndBar");
            return (Criteria) this;
        }

        public Criteria andLineEndBarBetween(String value1, String value2) {
            addCriterion("line_end_bar between", value1, value2, "lineEndBar");
            return (Criteria) this;
        }

        public Criteria andLineEndBarNotBetween(String value1, String value2) {
            addCriterion("line_end_bar not between", value1, value2, "lineEndBar");
            return (Criteria) this;
        }

        public Criteria andLineBarNumberIsNull() {
            addCriterion("line_bar_number is null");
            return (Criteria) this;
        }

        public Criteria andLineBarNumberIsNotNull() {
            addCriterion("line_bar_number is not null");
            return (Criteria) this;
        }

        public Criteria andLineBarNumberEqualTo(String value) {
            addCriterion("line_bar_number =", value, "lineBarNumber");
            return (Criteria) this;
        }

        public Criteria andLineBarNumberNotEqualTo(String value) {
            addCriterion("line_bar_number <>", value, "lineBarNumber");
            return (Criteria) this;
        }

        public Criteria andLineBarNumberGreaterThan(String value) {
            addCriterion("line_bar_number >", value, "lineBarNumber");
            return (Criteria) this;
        }

        public Criteria andLineBarNumberGreaterThanOrEqualTo(String value) {
            addCriterion("line_bar_number >=", value, "lineBarNumber");
            return (Criteria) this;
        }

        public Criteria andLineBarNumberLessThan(String value) {
            addCriterion("line_bar_number <", value, "lineBarNumber");
            return (Criteria) this;
        }

        public Criteria andLineBarNumberLessThanOrEqualTo(String value) {
            addCriterion("line_bar_number <=", value, "lineBarNumber");
            return (Criteria) this;
        }

        public Criteria andLineBarNumberLike(String value) {
            addCriterion("line_bar_number like", value, "lineBarNumber");
            return (Criteria) this;
        }

        public Criteria andLineBarNumberNotLike(String value) {
            addCriterion("line_bar_number not like", value, "lineBarNumber");
            return (Criteria) this;
        }

        public Criteria andLineBarNumberIn(List<String> values) {
            addCriterion("line_bar_number in", values, "lineBarNumber");
            return (Criteria) this;
        }

        public Criteria andLineBarNumberNotIn(List<String> values) {
            addCriterion("line_bar_number not in", values, "lineBarNumber");
            return (Criteria) this;
        }

        public Criteria andLineBarNumberBetween(String value1, String value2) {
            addCriterion("line_bar_number between", value1, value2, "lineBarNumber");
            return (Criteria) this;
        }

        public Criteria andLineBarNumberNotBetween(String value1, String value2) {
            addCriterion("line_bar_number not between", value1, value2, "lineBarNumber");
            return (Criteria) this;
        }

        public Criteria andLineStateIsNull() {
            addCriterion("line_state is null");
            return (Criteria) this;
        }

        public Criteria andLineStateIsNotNull() {
            addCriterion("line_state is not null");
            return (Criteria) this;
        }

        public Criteria andLineStateEqualTo(String value) {
            addCriterion("line_state =", value, "lineState");
            return (Criteria) this;
        }

        public Criteria andLineStateNotEqualTo(String value) {
            addCriterion("line_state <>", value, "lineState");
            return (Criteria) this;
        }

        public Criteria andLineStateGreaterThan(String value) {
            addCriterion("line_state >", value, "lineState");
            return (Criteria) this;
        }

        public Criteria andLineStateGreaterThanOrEqualTo(String value) {
            addCriterion("line_state >=", value, "lineState");
            return (Criteria) this;
        }

        public Criteria andLineStateLessThan(String value) {
            addCriterion("line_state <", value, "lineState");
            return (Criteria) this;
        }

        public Criteria andLineStateLessThanOrEqualTo(String value) {
            addCriterion("line_state <=", value, "lineState");
            return (Criteria) this;
        }

        public Criteria andLineStateLike(String value) {
            addCriterion("line_state like", value, "lineState");
            return (Criteria) this;
        }

        public Criteria andLineStateNotLike(String value) {
            addCriterion("line_state not like", value, "lineState");
            return (Criteria) this;
        }

        public Criteria andLineStateIn(List<String> values) {
            addCriterion("line_state in", values, "lineState");
            return (Criteria) this;
        }

        public Criteria andLineStateNotIn(List<String> values) {
            addCriterion("line_state not in", values, "lineState");
            return (Criteria) this;
        }

        public Criteria andLineStateBetween(String value1, String value2) {
            addCriterion("line_state between", value1, value2, "lineState");
            return (Criteria) this;
        }

        public Criteria andLineStateNotBetween(String value1, String value2) {
            addCriterion("line_state not between", value1, value2, "lineState");
            return (Criteria) this;
        }

        public Criteria andLineRemarkIsNull() {
            addCriterion("line_remark is null");
            return (Criteria) this;
        }

        public Criteria andLineRemarkIsNotNull() {
            addCriterion("line_remark is not null");
            return (Criteria) this;
        }

        public Criteria andLineRemarkEqualTo(String value) {
            addCriterion("line_remark =", value, "lineRemark");
            return (Criteria) this;
        }

        public Criteria andLineRemarkNotEqualTo(String value) {
            addCriterion("line_remark <>", value, "lineRemark");
            return (Criteria) this;
        }

        public Criteria andLineRemarkGreaterThan(String value) {
            addCriterion("line_remark >", value, "lineRemark");
            return (Criteria) this;
        }

        public Criteria andLineRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("line_remark >=", value, "lineRemark");
            return (Criteria) this;
        }

        public Criteria andLineRemarkLessThan(String value) {
            addCriterion("line_remark <", value, "lineRemark");
            return (Criteria) this;
        }

        public Criteria andLineRemarkLessThanOrEqualTo(String value) {
            addCriterion("line_remark <=", value, "lineRemark");
            return (Criteria) this;
        }

        public Criteria andLineRemarkLike(String value) {
            addCriterion("line_remark like", value, "lineRemark");
            return (Criteria) this;
        }

        public Criteria andLineRemarkNotLike(String value) {
            addCriterion("line_remark not like", value, "lineRemark");
            return (Criteria) this;
        }

        public Criteria andLineRemarkIn(List<String> values) {
            addCriterion("line_remark in", values, "lineRemark");
            return (Criteria) this;
        }

        public Criteria andLineRemarkNotIn(List<String> values) {
            addCriterion("line_remark not in", values, "lineRemark");
            return (Criteria) this;
        }

        public Criteria andLineRemarkBetween(String value1, String value2) {
            addCriterion("line_remark between", value1, value2, "lineRemark");
            return (Criteria) this;
        }

        public Criteria andLineRemarkNotBetween(String value1, String value2) {
            addCriterion("line_remark not between", value1, value2, "lineRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table line
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 23 09:16:48 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table line
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}