package com.doit.pojo;

public class LineUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_user.id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_user.user_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_user.line_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String lineCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_user.id
     *
     * @return the value of line_user.id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_user.id
     *
     * @param id the value for line_user.id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_user.user_id
     *
     * @return the value of line_user.user_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_user.user_id
     *
     * @param userId the value for line_user.user_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_user.line_code
     *
     * @return the value of line_user.line_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getLineCode() {
        return lineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_user.line_code
     *
     * @param lineCode the value for line_user.line_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setLineCode(String lineCode) {
        this.lineCode = lineCode;
    }
}