package com.doit.pojo;

import java.util.Date;

public class Line {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.line_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String lineCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.line_name
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String lineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.line_length
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Integer lineLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.line_rundate
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Date lineRundate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.line_voltage_level
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String lineVoltageLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.line_start_bar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String lineStartBar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.line_end_bar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String lineEndBar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.line_bar_number
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String lineBarNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.line_state
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String lineState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.line_remark
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String lineRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.line_code
     *
     * @return the value of line.line_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getLineCode() {
        return lineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.line_code
     *
     * @param lineCode the value for line.line_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setLineCode(String lineCode) {
        this.lineCode = lineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.line_name
     *
     * @return the value of line.line_name
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getLineName() {
        return lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.line_name
     *
     * @param lineName the value for line.line_name
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setLineName(String lineName) {
        this.lineName = lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.line_length
     *
     * @return the value of line.line_length
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Integer getLineLength() {
        return lineLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.line_length
     *
     * @param lineLength the value for line.line_length
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setLineLength(Integer lineLength) {
        this.lineLength = lineLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.line_rundate
     *
     * @return the value of line.line_rundate
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Date getLineRundate() {
        return lineRundate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.line_rundate
     *
     * @param lineRundate the value for line.line_rundate
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setLineRundate(Date lineRundate) {
        this.lineRundate = lineRundate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.line_voltage_level
     *
     * @return the value of line.line_voltage_level
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getLineVoltageLevel() {
        return lineVoltageLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.line_voltage_level
     *
     * @param lineVoltageLevel the value for line.line_voltage_level
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setLineVoltageLevel(String lineVoltageLevel) {
        this.lineVoltageLevel = lineVoltageLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.line_start_bar
     *
     * @return the value of line.line_start_bar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getLineStartBar() {
        return lineStartBar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.line_start_bar
     *
     * @param lineStartBar the value for line.line_start_bar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setLineStartBar(String lineStartBar) {
        this.lineStartBar = lineStartBar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.line_end_bar
     *
     * @return the value of line.line_end_bar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getLineEndBar() {
        return lineEndBar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.line_end_bar
     *
     * @param lineEndBar the value for line.line_end_bar
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setLineEndBar(String lineEndBar) {
        this.lineEndBar = lineEndBar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.line_bar_number
     *
     * @return the value of line.line_bar_number
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getLineBarNumber() {
        return lineBarNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.line_bar_number
     *
     * @param lineBarNumber the value for line.line_bar_number
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setLineBarNumber(String lineBarNumber) {
        this.lineBarNumber = lineBarNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.line_state
     *
     * @return the value of line.line_state
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getLineState() {
        return lineState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.line_state
     *
     * @param lineState the value for line.line_state
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setLineState(String lineState) {
        this.lineState = lineState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.line_remark
     *
     * @return the value of line.line_remark
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getLineRemark() {
        return lineRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.line_remark
     *
     * @param lineRemark the value for line.line_remark
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setLineRemark(String lineRemark) {
        this.lineRemark = lineRemark;
    }
}