package com.doit.pojo;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_info
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String roleInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_id
     *
     * @return the value of role.role_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_id
     *
     * @param roleId the value for role.role_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_info
     *
     * @return the value of role.role_info
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getRoleInfo() {
        return roleInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_info
     *
     * @param roleInfo the value for role.role_info
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setRoleInfo(String roleInfo) {
        this.roleInfo = roleInfo;
    }
}