package com.doit.pojo;

import java.util.Date;

public class ServiceResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_result.service_result_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String serviceResultCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_result.service_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String serviceTaskCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_result.service_result_description
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String serviceResultDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_result.service_result_state
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String serviceResultState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_result.service_result_complete_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Date serviceResultCompleteDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_result.defect_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Integer defectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_result.service_result_code
     *
     * @return the value of service_result.service_result_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getServiceResultCode() {
        return serviceResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_result.service_result_code
     *
     * @param serviceResultCode the value for service_result.service_result_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setServiceResultCode(String serviceResultCode) {
        this.serviceResultCode = serviceResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_result.service_task_code
     *
     * @return the value of service_result.service_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getServiceTaskCode() {
        return serviceTaskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_result.service_task_code
     *
     * @param serviceTaskCode the value for service_result.service_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setServiceTaskCode(String serviceTaskCode) {
        this.serviceTaskCode = serviceTaskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_result.service_result_description
     *
     * @return the value of service_result.service_result_description
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getServiceResultDescription() {
        return serviceResultDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_result.service_result_description
     *
     * @param serviceResultDescription the value for service_result.service_result_description
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setServiceResultDescription(String serviceResultDescription) {
        this.serviceResultDescription = serviceResultDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_result.service_result_state
     *
     * @return the value of service_result.service_result_state
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getServiceResultState() {
        return serviceResultState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_result.service_result_state
     *
     * @param serviceResultState the value for service_result.service_result_state
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setServiceResultState(String serviceResultState) {
        this.serviceResultState = serviceResultState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_result.service_result_complete_date
     *
     * @return the value of service_result.service_result_complete_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Date getServiceResultCompleteDate() {
        return serviceResultCompleteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_result.service_result_complete_date
     *
     * @param serviceResultCompleteDate the value for service_result.service_result_complete_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setServiceResultCompleteDate(Date serviceResultCompleteDate) {
        this.serviceResultCompleteDate = serviceResultCompleteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_result.defect_id
     *
     * @return the value of service_result.defect_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Integer getDefectId() {
        return defectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_result.defect_id
     *
     * @param defectId the value for service_result.defect_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setDefectId(Integer defectId) {
        this.defectId = defectId;
    }
}