package com.doit.pojo;

import java.util.Date;

public class ServiceTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_task.service_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String serviceTaskCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_task.service_task_name
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String serviceTaskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_task.defect_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Integer defectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_task.user_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_task.service_task_release_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Date serviceTaskReleaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_task.service_task_description
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String serviceTaskDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_task.service_task_code
     *
     * @return the value of service_task.service_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getServiceTaskCode() {
        return serviceTaskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_task.service_task_code
     *
     * @param serviceTaskCode the value for service_task.service_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setServiceTaskCode(String serviceTaskCode) {
        this.serviceTaskCode = serviceTaskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_task.service_task_name
     *
     * @return the value of service_task.service_task_name
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getServiceTaskName() {
        return serviceTaskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_task.service_task_name
     *
     * @param serviceTaskName the value for service_task.service_task_name
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setServiceTaskName(String serviceTaskName) {
        this.serviceTaskName = serviceTaskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_task.defect_id
     *
     * @return the value of service_task.defect_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Integer getDefectId() {
        return defectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_task.defect_id
     *
     * @param defectId the value for service_task.defect_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setDefectId(Integer defectId) {
        this.defectId = defectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_task.user_id
     *
     * @return the value of service_task.user_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_task.user_id
     *
     * @param userId the value for service_task.user_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_task.service_task_release_date
     *
     * @return the value of service_task.service_task_release_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Date getServiceTaskReleaseDate() {
        return serviceTaskReleaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_task.service_task_release_date
     *
     * @param serviceTaskReleaseDate the value for service_task.service_task_release_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setServiceTaskReleaseDate(Date serviceTaskReleaseDate) {
        this.serviceTaskReleaseDate = serviceTaskReleaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_task.service_task_description
     *
     * @return the value of service_task.service_task_description
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getServiceTaskDescription() {
        return serviceTaskDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_task.service_task_description
     *
     * @param serviceTaskDescription the value for service_task.service_task_description
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setServiceTaskDescription(String serviceTaskDescription) {
        this.serviceTaskDescription = serviceTaskDescription;
    }
}