package com.doit.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ServiceResultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public ServiceResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andServiceResultCodeIsNull() {
            addCriterion("service_result_code is null");
            return (Criteria) this;
        }

        public Criteria andServiceResultCodeIsNotNull() {
            addCriterion("service_result_code is not null");
            return (Criteria) this;
        }

        public Criteria andServiceResultCodeEqualTo(String value) {
            addCriterion("service_result_code =", value, "serviceResultCode");
            return (Criteria) this;
        }

        public Criteria andServiceResultCodeNotEqualTo(String value) {
            addCriterion("service_result_code <>", value, "serviceResultCode");
            return (Criteria) this;
        }

        public Criteria andServiceResultCodeGreaterThan(String value) {
            addCriterion("service_result_code >", value, "serviceResultCode");
            return (Criteria) this;
        }

        public Criteria andServiceResultCodeGreaterThanOrEqualTo(String value) {
            addCriterion("service_result_code >=", value, "serviceResultCode");
            return (Criteria) this;
        }

        public Criteria andServiceResultCodeLessThan(String value) {
            addCriterion("service_result_code <", value, "serviceResultCode");
            return (Criteria) this;
        }

        public Criteria andServiceResultCodeLessThanOrEqualTo(String value) {
            addCriterion("service_result_code <=", value, "serviceResultCode");
            return (Criteria) this;
        }

        public Criteria andServiceResultCodeLike(String value) {
            addCriterion("service_result_code like", value, "serviceResultCode");
            return (Criteria) this;
        }

        public Criteria andServiceResultCodeNotLike(String value) {
            addCriterion("service_result_code not like", value, "serviceResultCode");
            return (Criteria) this;
        }

        public Criteria andServiceResultCodeIn(List<String> values) {
            addCriterion("service_result_code in", values, "serviceResultCode");
            return (Criteria) this;
        }

        public Criteria andServiceResultCodeNotIn(List<String> values) {
            addCriterion("service_result_code not in", values, "serviceResultCode");
            return (Criteria) this;
        }

        public Criteria andServiceResultCodeBetween(String value1, String value2) {
            addCriterion("service_result_code between", value1, value2, "serviceResultCode");
            return (Criteria) this;
        }

        public Criteria andServiceResultCodeNotBetween(String value1, String value2) {
            addCriterion("service_result_code not between", value1, value2, "serviceResultCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeIsNull() {
            addCriterion("service_task_code is null");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeIsNotNull() {
            addCriterion("service_task_code is not null");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeEqualTo(String value) {
            addCriterion("service_task_code =", value, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeNotEqualTo(String value) {
            addCriterion("service_task_code <>", value, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeGreaterThan(String value) {
            addCriterion("service_task_code >", value, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeGreaterThanOrEqualTo(String value) {
            addCriterion("service_task_code >=", value, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeLessThan(String value) {
            addCriterion("service_task_code <", value, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeLessThanOrEqualTo(String value) {
            addCriterion("service_task_code <=", value, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeLike(String value) {
            addCriterion("service_task_code like", value, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeNotLike(String value) {
            addCriterion("service_task_code not like", value, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeIn(List<String> values) {
            addCriterion("service_task_code in", values, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeNotIn(List<String> values) {
            addCriterion("service_task_code not in", values, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeBetween(String value1, String value2) {
            addCriterion("service_task_code between", value1, value2, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeNotBetween(String value1, String value2) {
            addCriterion("service_task_code not between", value1, value2, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceResultDescriptionIsNull() {
            addCriterion("service_result_description is null");
            return (Criteria) this;
        }

        public Criteria andServiceResultDescriptionIsNotNull() {
            addCriterion("service_result_description is not null");
            return (Criteria) this;
        }

        public Criteria andServiceResultDescriptionEqualTo(String value) {
            addCriterion("service_result_description =", value, "serviceResultDescription");
            return (Criteria) this;
        }

        public Criteria andServiceResultDescriptionNotEqualTo(String value) {
            addCriterion("service_result_description <>", value, "serviceResultDescription");
            return (Criteria) this;
        }

        public Criteria andServiceResultDescriptionGreaterThan(String value) {
            addCriterion("service_result_description >", value, "serviceResultDescription");
            return (Criteria) this;
        }

        public Criteria andServiceResultDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("service_result_description >=", value, "serviceResultDescription");
            return (Criteria) this;
        }

        public Criteria andServiceResultDescriptionLessThan(String value) {
            addCriterion("service_result_description <", value, "serviceResultDescription");
            return (Criteria) this;
        }

        public Criteria andServiceResultDescriptionLessThanOrEqualTo(String value) {
            addCriterion("service_result_description <=", value, "serviceResultDescription");
            return (Criteria) this;
        }

        public Criteria andServiceResultDescriptionLike(String value) {
            addCriterion("service_result_description like", value, "serviceResultDescription");
            return (Criteria) this;
        }

        public Criteria andServiceResultDescriptionNotLike(String value) {
            addCriterion("service_result_description not like", value, "serviceResultDescription");
            return (Criteria) this;
        }

        public Criteria andServiceResultDescriptionIn(List<String> values) {
            addCriterion("service_result_description in", values, "serviceResultDescription");
            return (Criteria) this;
        }

        public Criteria andServiceResultDescriptionNotIn(List<String> values) {
            addCriterion("service_result_description not in", values, "serviceResultDescription");
            return (Criteria) this;
        }

        public Criteria andServiceResultDescriptionBetween(String value1, String value2) {
            addCriterion("service_result_description between", value1, value2, "serviceResultDescription");
            return (Criteria) this;
        }

        public Criteria andServiceResultDescriptionNotBetween(String value1, String value2) {
            addCriterion("service_result_description not between", value1, value2, "serviceResultDescription");
            return (Criteria) this;
        }

        public Criteria andServiceResultStateIsNull() {
            addCriterion("service_result_state is null");
            return (Criteria) this;
        }

        public Criteria andServiceResultStateIsNotNull() {
            addCriterion("service_result_state is not null");
            return (Criteria) this;
        }

        public Criteria andServiceResultStateEqualTo(String value) {
            addCriterion("service_result_state =", value, "serviceResultState");
            return (Criteria) this;
        }

        public Criteria andServiceResultStateNotEqualTo(String value) {
            addCriterion("service_result_state <>", value, "serviceResultState");
            return (Criteria) this;
        }

        public Criteria andServiceResultStateGreaterThan(String value) {
            addCriterion("service_result_state >", value, "serviceResultState");
            return (Criteria) this;
        }

        public Criteria andServiceResultStateGreaterThanOrEqualTo(String value) {
            addCriterion("service_result_state >=", value, "serviceResultState");
            return (Criteria) this;
        }

        public Criteria andServiceResultStateLessThan(String value) {
            addCriterion("service_result_state <", value, "serviceResultState");
            return (Criteria) this;
        }

        public Criteria andServiceResultStateLessThanOrEqualTo(String value) {
            addCriterion("service_result_state <=", value, "serviceResultState");
            return (Criteria) this;
        }

        public Criteria andServiceResultStateLike(String value) {
            addCriterion("service_result_state like", value, "serviceResultState");
            return (Criteria) this;
        }

        public Criteria andServiceResultStateNotLike(String value) {
            addCriterion("service_result_state not like", value, "serviceResultState");
            return (Criteria) this;
        }

        public Criteria andServiceResultStateIn(List<String> values) {
            addCriterion("service_result_state in", values, "serviceResultState");
            return (Criteria) this;
        }

        public Criteria andServiceResultStateNotIn(List<String> values) {
            addCriterion("service_result_state not in", values, "serviceResultState");
            return (Criteria) this;
        }

        public Criteria andServiceResultStateBetween(String value1, String value2) {
            addCriterion("service_result_state between", value1, value2, "serviceResultState");
            return (Criteria) this;
        }

        public Criteria andServiceResultStateNotBetween(String value1, String value2) {
            addCriterion("service_result_state not between", value1, value2, "serviceResultState");
            return (Criteria) this;
        }

        public Criteria andServiceResultCompleteDateIsNull() {
            addCriterion("service_result_complete_date is null");
            return (Criteria) this;
        }

        public Criteria andServiceResultCompleteDateIsNotNull() {
            addCriterion("service_result_complete_date is not null");
            return (Criteria) this;
        }

        public Criteria andServiceResultCompleteDateEqualTo(Date value) {
            addCriterionForJDBCDate("service_result_complete_date =", value, "serviceResultCompleteDate");
            return (Criteria) this;
        }

        public Criteria andServiceResultCompleteDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("service_result_complete_date <>", value, "serviceResultCompleteDate");
            return (Criteria) this;
        }

        public Criteria andServiceResultCompleteDateGreaterThan(Date value) {
            addCriterionForJDBCDate("service_result_complete_date >", value, "serviceResultCompleteDate");
            return (Criteria) this;
        }

        public Criteria andServiceResultCompleteDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("service_result_complete_date >=", value, "serviceResultCompleteDate");
            return (Criteria) this;
        }

        public Criteria andServiceResultCompleteDateLessThan(Date value) {
            addCriterionForJDBCDate("service_result_complete_date <", value, "serviceResultCompleteDate");
            return (Criteria) this;
        }

        public Criteria andServiceResultCompleteDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("service_result_complete_date <=", value, "serviceResultCompleteDate");
            return (Criteria) this;
        }

        public Criteria andServiceResultCompleteDateIn(List<Date> values) {
            addCriterionForJDBCDate("service_result_complete_date in", values, "serviceResultCompleteDate");
            return (Criteria) this;
        }

        public Criteria andServiceResultCompleteDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("service_result_complete_date not in", values, "serviceResultCompleteDate");
            return (Criteria) this;
        }

        public Criteria andServiceResultCompleteDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("service_result_complete_date between", value1, value2, "serviceResultCompleteDate");
            return (Criteria) this;
        }

        public Criteria andServiceResultCompleteDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("service_result_complete_date not between", value1, value2, "serviceResultCompleteDate");
            return (Criteria) this;
        }

        public Criteria andDefectIdIsNull() {
            addCriterion("defect_id is null");
            return (Criteria) this;
        }

        public Criteria andDefectIdIsNotNull() {
            addCriterion("defect_id is not null");
            return (Criteria) this;
        }

        public Criteria andDefectIdEqualTo(Integer value) {
            addCriterion("defect_id =", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdNotEqualTo(Integer value) {
            addCriterion("defect_id <>", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdGreaterThan(Integer value) {
            addCriterion("defect_id >", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("defect_id >=", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdLessThan(Integer value) {
            addCriterion("defect_id <", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdLessThanOrEqualTo(Integer value) {
            addCriterion("defect_id <=", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdIn(List<Integer> values) {
            addCriterion("defect_id in", values, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdNotIn(List<Integer> values) {
            addCriterion("defect_id not in", values, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdBetween(Integer value1, Integer value2) {
            addCriterion("defect_id between", value1, value2, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("defect_id not between", value1, value2, "defectId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table service_result
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 23 09:16:48 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table service_result
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}