package com.doit.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ServiceTaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public ServiceTaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andServiceTaskCodeIsNull() {
            addCriterion("service_task_code is null");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeIsNotNull() {
            addCriterion("service_task_code is not null");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeEqualTo(String value) {
            addCriterion("service_task_code =", value, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeNotEqualTo(String value) {
            addCriterion("service_task_code <>", value, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeGreaterThan(String value) {
            addCriterion("service_task_code >", value, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeGreaterThanOrEqualTo(String value) {
            addCriterion("service_task_code >=", value, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeLessThan(String value) {
            addCriterion("service_task_code <", value, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeLessThanOrEqualTo(String value) {
            addCriterion("service_task_code <=", value, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeLike(String value) {
            addCriterion("service_task_code like", value, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeNotLike(String value) {
            addCriterion("service_task_code not like", value, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeIn(List<String> values) {
            addCriterion("service_task_code in", values, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeNotIn(List<String> values) {
            addCriterion("service_task_code not in", values, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeBetween(String value1, String value2) {
            addCriterion("service_task_code between", value1, value2, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskCodeNotBetween(String value1, String value2) {
            addCriterion("service_task_code not between", value1, value2, "serviceTaskCode");
            return (Criteria) this;
        }

        public Criteria andServiceTaskNameIsNull() {
            addCriterion("service_task_name is null");
            return (Criteria) this;
        }

        public Criteria andServiceTaskNameIsNotNull() {
            addCriterion("service_task_name is not null");
            return (Criteria) this;
        }

        public Criteria andServiceTaskNameEqualTo(String value) {
            addCriterion("service_task_name =", value, "serviceTaskName");
            return (Criteria) this;
        }

        public Criteria andServiceTaskNameNotEqualTo(String value) {
            addCriterion("service_task_name <>", value, "serviceTaskName");
            return (Criteria) this;
        }

        public Criteria andServiceTaskNameGreaterThan(String value) {
            addCriterion("service_task_name >", value, "serviceTaskName");
            return (Criteria) this;
        }

        public Criteria andServiceTaskNameGreaterThanOrEqualTo(String value) {
            addCriterion("service_task_name >=", value, "serviceTaskName");
            return (Criteria) this;
        }

        public Criteria andServiceTaskNameLessThan(String value) {
            addCriterion("service_task_name <", value, "serviceTaskName");
            return (Criteria) this;
        }

        public Criteria andServiceTaskNameLessThanOrEqualTo(String value) {
            addCriterion("service_task_name <=", value, "serviceTaskName");
            return (Criteria) this;
        }

        public Criteria andServiceTaskNameLike(String value) {
            addCriterion("service_task_name like", value, "serviceTaskName");
            return (Criteria) this;
        }

        public Criteria andServiceTaskNameNotLike(String value) {
            addCriterion("service_task_name not like", value, "serviceTaskName");
            return (Criteria) this;
        }

        public Criteria andServiceTaskNameIn(List<String> values) {
            addCriterion("service_task_name in", values, "serviceTaskName");
            return (Criteria) this;
        }

        public Criteria andServiceTaskNameNotIn(List<String> values) {
            addCriterion("service_task_name not in", values, "serviceTaskName");
            return (Criteria) this;
        }

        public Criteria andServiceTaskNameBetween(String value1, String value2) {
            addCriterion("service_task_name between", value1, value2, "serviceTaskName");
            return (Criteria) this;
        }

        public Criteria andServiceTaskNameNotBetween(String value1, String value2) {
            addCriterion("service_task_name not between", value1, value2, "serviceTaskName");
            return (Criteria) this;
        }

        public Criteria andDefectIdIsNull() {
            addCriterion("defect_id is null");
            return (Criteria) this;
        }

        public Criteria andDefectIdIsNotNull() {
            addCriterion("defect_id is not null");
            return (Criteria) this;
        }

        public Criteria andDefectIdEqualTo(Integer value) {
            addCriterion("defect_id =", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdNotEqualTo(Integer value) {
            addCriterion("defect_id <>", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdGreaterThan(Integer value) {
            addCriterion("defect_id >", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("defect_id >=", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdLessThan(Integer value) {
            addCriterion("defect_id <", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdLessThanOrEqualTo(Integer value) {
            addCriterion("defect_id <=", value, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdIn(List<Integer> values) {
            addCriterion("defect_id in", values, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdNotIn(List<Integer> values) {
            addCriterion("defect_id not in", values, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdBetween(Integer value1, Integer value2) {
            addCriterion("defect_id between", value1, value2, "defectId");
            return (Criteria) this;
        }

        public Criteria andDefectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("defect_id not between", value1, value2, "defectId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andServiceTaskReleaseDateIsNull() {
            addCriterion("service_task_release_date is null");
            return (Criteria) this;
        }

        public Criteria andServiceTaskReleaseDateIsNotNull() {
            addCriterion("service_task_release_date is not null");
            return (Criteria) this;
        }

        public Criteria andServiceTaskReleaseDateEqualTo(Date value) {
            addCriterionForJDBCDate("service_task_release_date =", value, "serviceTaskReleaseDate");
            return (Criteria) this;
        }

        public Criteria andServiceTaskReleaseDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("service_task_release_date <>", value, "serviceTaskReleaseDate");
            return (Criteria) this;
        }

        public Criteria andServiceTaskReleaseDateGreaterThan(Date value) {
            addCriterionForJDBCDate("service_task_release_date >", value, "serviceTaskReleaseDate");
            return (Criteria) this;
        }

        public Criteria andServiceTaskReleaseDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("service_task_release_date >=", value, "serviceTaskReleaseDate");
            return (Criteria) this;
        }

        public Criteria andServiceTaskReleaseDateLessThan(Date value) {
            addCriterionForJDBCDate("service_task_release_date <", value, "serviceTaskReleaseDate");
            return (Criteria) this;
        }

        public Criteria andServiceTaskReleaseDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("service_task_release_date <=", value, "serviceTaskReleaseDate");
            return (Criteria) this;
        }

        public Criteria andServiceTaskReleaseDateIn(List<Date> values) {
            addCriterionForJDBCDate("service_task_release_date in", values, "serviceTaskReleaseDate");
            return (Criteria) this;
        }

        public Criteria andServiceTaskReleaseDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("service_task_release_date not in", values, "serviceTaskReleaseDate");
            return (Criteria) this;
        }

        public Criteria andServiceTaskReleaseDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("service_task_release_date between", value1, value2, "serviceTaskReleaseDate");
            return (Criteria) this;
        }

        public Criteria andServiceTaskReleaseDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("service_task_release_date not between", value1, value2, "serviceTaskReleaseDate");
            return (Criteria) this;
        }

        public Criteria andServiceTaskDescriptionIsNull() {
            addCriterion("service_task_description is null");
            return (Criteria) this;
        }

        public Criteria andServiceTaskDescriptionIsNotNull() {
            addCriterion("service_task_description is not null");
            return (Criteria) this;
        }

        public Criteria andServiceTaskDescriptionEqualTo(String value) {
            addCriterion("service_task_description =", value, "serviceTaskDescription");
            return (Criteria) this;
        }

        public Criteria andServiceTaskDescriptionNotEqualTo(String value) {
            addCriterion("service_task_description <>", value, "serviceTaskDescription");
            return (Criteria) this;
        }

        public Criteria andServiceTaskDescriptionGreaterThan(String value) {
            addCriterion("service_task_description >", value, "serviceTaskDescription");
            return (Criteria) this;
        }

        public Criteria andServiceTaskDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("service_task_description >=", value, "serviceTaskDescription");
            return (Criteria) this;
        }

        public Criteria andServiceTaskDescriptionLessThan(String value) {
            addCriterion("service_task_description <", value, "serviceTaskDescription");
            return (Criteria) this;
        }

        public Criteria andServiceTaskDescriptionLessThanOrEqualTo(String value) {
            addCriterion("service_task_description <=", value, "serviceTaskDescription");
            return (Criteria) this;
        }

        public Criteria andServiceTaskDescriptionLike(String value) {
            addCriterion("service_task_description like", value, "serviceTaskDescription");
            return (Criteria) this;
        }

        public Criteria andServiceTaskDescriptionNotLike(String value) {
            addCriterion("service_task_description not like", value, "serviceTaskDescription");
            return (Criteria) this;
        }

        public Criteria andServiceTaskDescriptionIn(List<String> values) {
            addCriterion("service_task_description in", values, "serviceTaskDescription");
            return (Criteria) this;
        }

        public Criteria andServiceTaskDescriptionNotIn(List<String> values) {
            addCriterion("service_task_description not in", values, "serviceTaskDescription");
            return (Criteria) this;
        }

        public Criteria andServiceTaskDescriptionBetween(String value1, String value2) {
            addCriterion("service_task_description between", value1, value2, "serviceTaskDescription");
            return (Criteria) this;
        }

        public Criteria andServiceTaskDescriptionNotBetween(String value1, String value2) {
            addCriterion("service_task_description not between", value1, value2, "serviceTaskDescription");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table service_task
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 23 09:16:48 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table service_task
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}