package com.doit.pojo;

public class TaskUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_user.id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_user.user_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_user.inspection_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String inspectionTaskCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_user.id
     *
     * @return the value of task_user.id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_user.id
     *
     * @param id the value for task_user.id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_user.user_id
     *
     * @return the value of task_user.user_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_user.user_id
     *
     * @param userId the value for task_user.user_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_user.inspection_task_code
     *
     * @return the value of task_user.inspection_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getInspectionTaskCode() {
        return inspectionTaskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_user.inspection_task_code
     *
     * @param inspectionTaskCode the value for task_user.inspection_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setInspectionTaskCode(String inspectionTaskCode) {
        this.inspectionTaskCode = inspectionTaskCode;
    }
}