package com.doit.pojo;

public class TaskResut {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_resut.id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_resut.inspection_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String inspectionTaskCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_resut.inspection_result_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Integer inspectionResultId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_resut.id
     *
     * @return the value of task_resut.id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_resut.id
     *
     * @param id the value for task_resut.id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_resut.inspection_task_code
     *
     * @return the value of task_resut.inspection_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getInspectionTaskCode() {
        return inspectionTaskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_resut.inspection_task_code
     *
     * @param inspectionTaskCode the value for task_resut.inspection_task_code
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setInspectionTaskCode(String inspectionTaskCode) {
        this.inspectionTaskCode = inspectionTaskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_resut.inspection_result_id
     *
     * @return the value of task_resut.inspection_result_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Integer getInspectionResultId() {
        return inspectionResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_resut.inspection_result_id
     *
     * @param inspectionResultId the value for task_resut.inspection_result_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setInspectionResultId(Integer inspectionResultId) {
        this.inspectionResultId = inspectionResultId;
    }
}