package com.doit.pojo;

public class Temp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.temp_key
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String tempKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.temp_value
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Integer tempValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.temp_key
     *
     * @return the value of temp.temp_key
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getTempKey() {
        return tempKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.temp_key
     *
     * @param tempKey the value for temp.temp_key
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setTempKey(String tempKey) {
        this.tempKey = tempKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.temp_value
     *
     * @return the value of temp.temp_value
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Integer getTempValue() {
        return tempValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.temp_value
     *
     * @param tempValue the value for temp.temp_value
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setTempValue(Integer tempValue) {
        this.tempValue = tempValue;
    }
}