package com.doit.pojo;

import java.util.Date;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_sex
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_birthday
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Date userBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_address
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String userAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_tel
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String userTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_email
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_entry_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Date userEntryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_leave_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Date userLeaveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_login_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    private Date userLoginDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_sex
     *
     * @return the value of user_info.user_sex
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_sex
     *
     * @param userSex the value for user_info.user_sex
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_birthday
     *
     * @return the value of user_info.user_birthday
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_birthday
     *
     * @param userBirthday the value for user_info.user_birthday
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_address
     *
     * @return the value of user_info.user_address
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_address
     *
     * @param userAddress the value for user_info.user_address
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_tel
     *
     * @return the value of user_info.user_tel
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_tel
     *
     * @param userTel the value for user_info.user_tel
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_email
     *
     * @return the value of user_info.user_email
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_email
     *
     * @param userEmail the value for user_info.user_email
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_entry_date
     *
     * @return the value of user_info.user_entry_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Date getUserEntryDate() {
        return userEntryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_entry_date
     *
     * @param userEntryDate the value for user_info.user_entry_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setUserEntryDate(Date userEntryDate) {
        this.userEntryDate = userEntryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_leave_date
     *
     * @return the value of user_info.user_leave_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Date getUserLeaveDate() {
        return userLeaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_leave_date
     *
     * @param userLeaveDate the value for user_info.user_leave_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setUserLeaveDate(Date userLeaveDate) {
        this.userLeaveDate = userLeaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_login_date
     *
     * @return the value of user_info.user_login_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public Date getUserLoginDate() {
        return userLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_login_date
     *
     * @param userLoginDate the value for user_info.user_login_date
     *
     * @mbg.generated Mon Oct 23 09:16:48 CST 2017
     */
    public void setUserLoginDate(Date userLoginDate) {
        this.userLoginDate = userLoginDate;
    }
}